spring:
  mail:
    default-encoding: UTF-8
    host: mail.vitautocity.by
    port: 587
    username: info@vitautocity.by
    password: "J0486Bor"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
