spring:
  mail:
    default-encoding: UTF-8
    host: *.by
    port: 587
    username: *
    password: "*"
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
