spring:
  mail:
    default-encoding: UTF-8
    host: mail.vitautocity.by
    port: 587
    username: *
    password: "*"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
